#!/bin/bash
#
# To be used with the suite of cray compilers (PrgEnv-cray).
# To get netcdf, add:
# module load cray-hdf5-parallel/1.10.0.1
# module load cray-netcdf-hdf5parallel/4.4.1.1

CC='cc'
FC='ftn'
F90C='ftn'

DEFINES='-DWORDLENGTH=4'
CPP='cpp -traditional -P'
EXTENDED_SRC_FLAG='-Mextend'
GET_FC_VERSION="-V"
CHECK_FOR_LAPACK=f


CFLAGS="$CFLAGS -shared -fPIC"
FFLAGS="$FFLAGS -shared -fPIC"

INCLUDES='-I/opt/cray/pe/mpt/default/gni/mpich-cray/9.0/include/ -I/opt/cray/pe/netcdf/default/crayclang/9.0/include/'
LIBS='-L/opt/cray/pe/netcdf/default/crayclang/9.0/lib/'

NOOPTFLAGS='-O0'
NOOPTFILES=''

if test "x$IEEE" = x ; then   #- with optimisation:
#   FOPTIM='-O2 -hfp3 -Oipa5' for less agressive optimization 
#   Be aware not all experiments pass the restart test with optimization 
    FOPTIM='-O3 -hfp3 -Oipa5'
else
    if test "x$DEVEL" = x ; then  #- no optimisation + IEEE :
      FOPTIM='-O0 -hfp0'
    else                          #- development/check options:
      FOPTIM='-O0 -hfp0'
      #FOPTIM="$FOPTIM -g -Rbc -rm -hmsgs -hnegmsgs"
    fi
fi

#- For big executable, this could help:
#FFLAGS='-h pic -dynamic'
#CFLAGS='-h pic -dynamic'

