#!/bin/bash
#
# To be used with the suite of cray compilers (PrgEnv-cray).
# To get netcdf, add:
# module load cray-hdf5-parallel/1.10.0.1
# module load cray-netcdf-hdf5parallel/4.4.1.1


CC='cc'
FC='ftn'
F90C='ftn'

DEFINES='-DWORDLENGTH=4 -D_BYTESWAPIO -DHAVE_LAPACK'
CPP='cpp -traditional -P'
EXTENDED_SRC_FLAG='-Mextend'
GET_FC_VERSION="-V"
CHECK_FOR_LAPACK=t

INCLUDES='-I/opt/cray/pe/mpt/7.7.3/gni/mpich-cray/8.6/include -I/opt/cray/pe/netcdf/4.6.1.3/CRAY/8.6/include'
LIBS='-L/opt/cray/pe/netcdf/4.6.1.3/CRAY/8.6/lib'

NOOPTFLAGS='-O0'
NOOPTFILES=''

if test "x$IEEE" = x ; then   #- with optimisation:
#   FOPTIM='-O2 -hfp3 -Oipa5' for less agressive optimization 
#   Be aware not all experiments pass the restart test with optimization 
    FOPTIM='-O3 -hfp0 -g'
else
    if test "x$DEVEL" = x ; then  #- no optimisation + IEEE :
      FOPTIM='-O0 -hfp0'
    else                          #- development/check options:
      FOPTIM='-O0 -hfp0'
      #FOPTIM="$FOPTIM -g -Rbc -rm -hmsgs -hnegmsgs"
    fi
fi

#- For big executable, this could help:
#FFLAGS='-h pic -dynamic'
#CFLAGS='-h pic -dynamic'

